dist: focal
language: node_js
node_js:
  - 18
services:
- docker

script:
- docker build -t udagram-api-feed ./project/udagram-api-feed
- docker build -t udagram-api-user ./project/udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t reverseproxy ./project/udagram-reverseproxy

- docker tag udagram-api-feed ngbinhan/udagram-api-feed:${TRAVIS_BUILD_NUMBER}
- docker tag udagram-api-user ngbinhan/udagram-api-user:${TRAVIS_BUILD_NUMBER}
- docker tag udagram-frontend ngbinhan/udagram-frontend:${TRAVIS_BUILD_NUMBER}
- docker tag reverseproxy ngbinhan/reverseproxy:${TRAVIS_BUILD_NUMBER}

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ngbinhan/udagram-api-feed:${TRAVIS_BUILD_NUMBER}
  - docker push ngbinhan/udagram-api-user:${TRAVIS_BUILD_NUMBER}
  - docker push ngbinhan/udagram-frontend:${TRAVIS_BUILD_NUMBER}
  - docker push ngbinhan/reverseproxy:${TRAVIS_BUILD_NUMBER}

