version: "3"
services:
  reverseproxy:
      image: reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: udagram-api-user:lastest
    environment:
      POSTGRES_USERNAME: annb16
      POSTGRES_PASSWORD: annb16udacity
      POSTGRES_HOST: course4db.cjrxlsrm7e2t.us-east-1.rds.amazonaws.com
      POSTGRES_DB: postgres
      AWS_BUCKET: annb16-cource4-bucket
      AWS_REGION: us-east-1
      AWS_PROFILE: annb16
      JWT_SECRET: testing
      URL: "http://localhost:8080"
  backend-feed:
    image: udagram-api-feed:lastest
    # volumes:
    #   - $HOME/.aws/:/root/.aws:ro
    environment:
      POSTGRES_USERNAME: annb16
      POSTGRES_PASSWORD: annb16udacity
      POSTGRES_HOST: course4db.cjrxlsrm7e2t.us-east-1.rds.amazonaws.com
      POSTGRES_DB: postgres
      AWS_BUCKET: annb16-cource4-bucket
      AWS_REGION: us-east-1
      AWS_PROFILE: annb16
      JWT_SECRET: testing
      URL: "http://localhost:8080"
  frontend:
    image: udagram-frontend:lastest
    ports:
      - "8100:80"